# Configuración del Servidor
sonar.host.url=http://localhost:9000

# Identificación del Proyecto
sonar.projectKey=test
sonar.projectName=Nombre de tu Proyecto
sonar.projectVersion=1.0

# Configuración de Código
sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8

# Reporte de Cobertura
sonar.python.coverage.reportPaths=coverage.xml

# Tests
sonar.tests=tests

# Exclusiones (Opcional pero recomendado)
# Evita que Sonar analice tus tests o entornos virtuales como código fuente
sonar.exclusions=**/venv/**, **/tests/**, **/setup.py