Table Owner [headercolor: #175e7a] {
	idOwner integer [ pk, increment, not null, unique ]
	name varchar(100)
	lastName varchar(255)
}

Table Space [headercolor: #175e7a] {
	idSpace integer [ pk, increment, not null, unique ]
	name varchar(100)
	description varchar(255)
	capacity integer
}

Table Reservation [headercolor: #175e7a] {
	idReservation integer [ pk, increment, not null, unique ]
}

Table SpaceReservation [headercolor: #175e7a] {
	idSpaceReservation integer [ pk, increment, not null, unique ]
}

Table OwnerSpaces [headercolor: #175e7a] {
	idOwnerSpaces integer [ pk, increment, not null, unique ]
}

